version: "1"
rules:
  - base: master
    upstream: getvoltage:master
    mergeMethod: hardreset
    mergeUnstable: false
  - base: v0.12.0-beta.rc1
    upstream: getvoltage:v0.12.0-beta.rc1
    mergeMethod: hardreset